services:
  redis:
    image: redis:8.8.0-alpine
    container_name: smiles-render-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: unless-stopped

  smiles-render-web:
    build: .
    container_name: smiles-render-web
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-worker:
    build: .
    container_name: smiles-render-worker
    working_dir: /app/src
    command: celery -A tasks worker --loglevel=info --pool=solo
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis-data:
    driver: local
